### ISSUE TITLE
zh_tw file

### ISSUE THREAD

**Issue by ghost** [vemerion/Runesword#2]
{
  "gui.runesword.no_sword": "把劍放入符文爐裡",
  "gui.runesword.slot_locked": "插槽鎖定",
  "item.runesword.runeforge_block_item": "符文爐",
  "block.runesword.runeforge_block": "符文爐",
  "item.runesword.fire_rune_item": "火符文",
  "item.runesword.water_rune_item": "水符文",
  "item.runesword.earth_rune_item": "地符文",
  "item.runesword.air_rune_item": "風符文",
  "item.runesword.blood_rune_item": "血符文",
  "tooltip.runesword.minor": "次要: ",
  "tooltip.runesword.major": "主要: ",
  "itemGroup.runesword": "Runesword"
}

**Comment by vemerion** [comment]
Thank you so much for this! I have now pushed a commit that adds the language file (commit 64e2d6eae5e7cc9dc8400025b345a47e23b6ac53).
